const data = [
    {
      key: '1',
      name: 'John Brown',
      age: 32,
      birthdate: '1993-05-15',
      country: 'England',
    },
    {
      key: '2',
      name: 'Jim Green',
      age: 42,
      birthdate: '1998-03-20',
      country: 'England',
    },
    {
      key: '3',
      name: 'Joe Black',
      age: 32,
      birthdate: '1998-07-22',
      country: 'England',
    },
    {
    key: '4',
    name: 'Alex Brown',
    age: 33,
    birthdate: '1998-07-22',
    country: 'Israel',
    },
    {
    key: '5',
    name: 'Lucy Fink',
    age: 36,
    birthdate: '1998-07-22',
    country: 'Israel',
    },
    {
    key: '6',
    name: 'Barbie Pink',
    age: 36,
    birthdate: '1998-07-22',
    country: 'United States of America',
    },
    {
        key: '7',
        name: 'Ken Blue',
        age: 39,
        birthdate: '1998-07-22',
        country: 'United States of America',
        },
        {
            key: '8',
            name: 'Oliver Puttnnum ',
            age: 55,
            birthdate: '1998-07-22',
            country: 'Brazil',
            },
            {
                key: '9',
                name: 'Macy Williams ',
                age: 55,
                birthdate: '1998-07-22',
                country: 'England',
                },
                {
                    key: '10',
                    name: 'Robert Williams ',
                    age: 58,
                    birthdate: '1998-07-22',
                    country: 'United States of America',
                    },
                    {
                        key: '11',
                        name: 'Serena Williams ',
                        age: 40,
                        birthdate: '1998-07-22',
                        country: 'United States of America',
                        },
                        {
                            key: '12',
                            name: 'Alex Edelman ',
                            age: 29,
                            birthdate: '1998-07-22',
                            country: 'United States of America',
                            },
                            {
                                key: '13',
                                name: 'Yaakov Jaffee ',
                                age: 37,
                                birthdate: '1998-07-22',
                                country: 'Israel',
                                },
  ];
  export default data